### ISSUE TITLE
AD2 remains exited after restart

### ISSUE THREAD

**Issue by keukenrol** [abcd567a/ad2#1]
Hi

I installed AD2 but am unable to get it to run. OS is raspbian bullseye (11) 64 bit on pi3b+.

sudo systemctl status ad2
● ad2.service - AcarSDeco2
     Loaded: loaded (/lib/systemd/system/ad2.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-04-25 18:16:58 CEST; 23s ago
    Process: 27323 ExecStart=/bin/bash /usr/share/ad2/ad2-start.sh (code=exited, status=127)
   Main PID: 27323 (code=exited, status=127)
        CPU: 17ms

I suppose the issue lies here:

./acarsdeco2 --help
./acarsdeco2: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory

Thus, searching for libudev yields:
sudo find / -name "*libudev*"
/var/cache/apt/archives/libudev-dev_247.3-7_arm64.deb
/var/cache/apt/archives/libudev1_247.3-7_arm64.deb
/var/lib/dpkg/info/libudev1:arm64.shlibs
/var/lib/dpkg/info/libudev1:arm64.triggers
/var/lib/dpkg/info/libudev1:arm64.list
/var/lib/dpkg/info/libudev1:arm64.md5sums
/var/lib/dpkg/info/libudev-dev:arm64.md5sums
/var/lib/dpkg/info/libudev1:arm64.symbols
/var/lib/dpkg/info/libudev-dev:arm64.list
/usr/include/libudev.h
/usr/lib/aarch64-linux-gnu/libudev.so.1
/usr/lib/aarch64-linux-gnu/libudev.so
/usr/lib/aarch64-linux-gnu/libudev.so.1.7.0
/usr/lib/aarch64-linux-gnu/pkgconfig/libudev.pc
/usr/share/doc/libudev-dev
/usr/share/doc/libudev1
/usr/share/man/man3/libudev.3.gz

**Comment by abcd567a** [comment]
This version of Acarsdeco installed is 32 bit. 
Please install 32 bit libudev

`sudo apt install libudev:armhf `

**EDIT** (based on feedback by @keukenrol) 

`sudo apt install libudev-dev:armhf  `

**Comment by keukenrol** [comment]
Worked with sudo apt-get install libudev-dev:armhf, as yours was not found. Thanks!

**Comment by abcd567a** [comment]
Thanks for feedback
