### ISSUE TITLE
ad2 error - cyclic service restart - PI3B+ debian bookworm arm 64 

### ISSUE THREAD

**Issue by mw0cqu** [abcd567a/ad2#3]
Ad2 installed as per the documentation

Service will not start / goes into cyclic restart 

Journalctl -u ad2 reveals: 

Started ad2.service - AcarSDeco2.
May 28 15:20:00 RadarPi acarsdeco2[9333]: /usr/share/ad2/acarsdeco2: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
May 28 15:20:00 RadarPi systemd[1]: ad2.service: Main process exited, code=exited, status=127/n/a
May 28 15:20:00 RadarPi systemd[1]: ad2.service: Failed with result 'exit-code'.
May 28 15:20:30 RadarPi systemd[1]: ad2.service: Scheduled restart job, restart counter is at 9.
May 28 15:20:30 RadarPi systemd[1]: Stopped ad2.service - AcarSDeco2.

libstdc++6  is installed:

sudo apt install libstdc++6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libstdc++6 is already the newest version (12.2.0-14).

Anticipating it might need the 32bit libc++6 I tried to install lib32c++6 . apt thinks no such package for 64bit arm

Any clues / suggestions please ?

Many thanks in advance

**Comment by abcd567a** [comment]
You have to install armhf version of `libstdc++6` as the version available on 64-bit (arm64) OS is not compatible with 32-bit acarsdeco2.

Use this command:
`sudo dpkg --add-architecture armhf  `
`sudo apt update `
`sudo apt install libstdc++6:armhf `
