### ISSUE TITLE
Unable to run Error re Shared libs

### ISSUE THREAD

**Issue by mgstu** [abcd567a/ad2#4]
Hi,

clean install and upon trying the basics to check my devices I get the below, I think it might be related to me running a 64bit Pi..

any ideas ? thanks !

admin@MASTPIplane:/usr/share/ad2 $ ./acarsdeco2 --device-list
./acarsdeco2: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

checking the status I always see, 

admin@MASTPIplane:~ $ sudo systemctl status ad2
○ ad2.service - AcarSDeco2
     Loaded: loaded (/lib/systemd/system/ad2.service; enabled; preset: enabled)
     Active: inactive (dead) (Result: exit-code) since Mon 2024-10-14 14:48:34 BST; 44min ago
   Duration: 17ms
    Process: 24351 ExecStart=/bin/bash /usr/share/ad2/ad2-start.sh (code=exited, status=127)
   Main PID: 24351 (code=exited, status=127)
        CPU: 16ms

**Comment by abcd567a** [comment]
The acarsdeco2 executeable is 32-bit
In 64-bit Bookworm, several libraries are either missing or placed in a different library folder than in 32-bit version of OS.

please issue following commands to fix the problem by (1) installing packages for missing items and (2) creating softlink to 32-bit armhf libraries in folder /usr/lib/ which the AcarsDeco2 accesses.

```
sudo apt install libc6-armhf-cross
sudo ln -sf /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 /usr/lib/ld-linux-armhf.so.3

sudo ln -sf /usr/arm-linux-gnueabihf/lib/libpthread.so.0 /usr/lib/libpthread.so.0

sudo ln -sf /usr/arm-linux-gnueabihf/lib/librt.so.1 /usr/lib/librt.so.1

sudo ln -sf /usr/arm-linux-gnueabihf/lib/libdl.so.2 /usr/lib/libdl.so.2 

sudo apt install libudev-dev:armhf
sudo ln -sf /usr/lib/arm-linux-gnueabihf/libudev.so.1 /usr/lib/libudev.so.1

sudo apt install gcc-12-cross-base libgcc-s1-armhf-cross
wget http://http.us.debian.org/debian/pool/main/g/gcc-12-cross/libstdc++6-armhf-cross_12.2.0-14cross1_all.deb \sudo dpkg -i libstdc++6-armhf-cross_12.2.0-14cross1_all.deb

wget http://http.us.debian.org/debian/pool/main/g/gcc-12-cross/libstdc++6-armhf-cross_12.2.0-14cross1_all.deb 
sudo dpkg -i libstdc++6-armhf-cross_12.2.0-14cross1_all.deb.1
sudo ln -sf /usr/arm-linux-gnueabihf/lib/libstdc++.so.6 /usr/lib/libstdc++.so.6 

```

### Later Addition:
After doing above workaround, you may get following error on running acarsdeco2 
`Error: sdr_open(): Device or resource busy`

Do following blacklisting to fix it:

`sudo nano /etc/modprobe.d/rtl_sdr.conf `

copy-paste following, save file,  and reboot
```
blacklist dvb_usb_rtl28xxu
blacklist dvb_usb_v2
blacklist rtl_2830
blacklist rtl_2832
blacklist r820t
```

**Comment by mgstu** [comment]
Thanks for the reply ! :) ok I've done all that, does all seem to go "ok", but still wont run, I get the below from the "sudo systemctl status ad2" command, any ideas ? really appreciated ! thanks 

admin@MASTPIplane:~ $ sudo systemctl status ad2
● ad2.service - AcarSDeco2
     Loaded: loaded (/lib/systemd/system/ad2.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2024-10-15 09:37:03 BST; 3s ago
    Process: 9840 ExecStart=/bin/bash /usr/share/ad2/ad2-start.sh (code=exited, status=139)
   Main PID: 9840 (code=exited, status=139)
        CPU: 142ms
admin@MASTPIplane:~ $

**Comment by abcd567a** [comment]
> Process: 9840 ExecStart=/bin/bash /usr/share/ad2/ad2-start.sh (code=exited, status=139)

**Reboot Pi and then check again.**

If a process exits with status code 139, it's because it received a SIGSEGV signal. The operating system terminated the application's process to guard against a memory integrity violation. It's important to investigate what's causing the segmentation errors if your application is terminating with code 139.

Sometimes this error occurs when the process is trying to open/read a file already open. It may be that you have manually run acarsdeco2 or a previous instance is still running. Rebooting Pi will close all open files & processes running in background.

**Comment by mgstu** [comment]
thanks, ok well a reboot hasent sorted it, ive not tried to manually run the app and dont beleive any other instances running, sooo slightly at a loss :(

admin@MASTPIplane:~ $ sudo systemctl status ad2
● ad2.service - AcarSDeco2
     Loaded: loaded (/lib/systemd/system/ad2.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2024-10-15 22:34:04 BST; 15s ago
    Process: 4839 ExecStart=/bin/bash /usr/share/ad2/ad2-start.sh (code=exited, status=139)
   Main PID: 4839 (code=exited, status=139)
        CPU: 147ms
admin@MASTPIplane:~ $

**Comment by abcd567a** [comment]
I am really at loss why acarsdeco2 is giving you segmentation fault.

I have installed it on Raspberry Pi Model 4 running "64-bit Raspberry Pi OS Bookworm", and using workaround for dependencies which I have posted above, and it works ok. Please see screenshot below.

![Screenshot_20241015_214210_Termux](https://github.com/user-attachments/assets/4330eb1d-5902-45cd-ad3e-767ad4b29c85)

**Comment by abcd567a** [comment]
(1) On recheking I found only following dependencies are required,

libudev-dev:armhf 
libstdc++6:armhf 

(2) I have now modified installation script and included installation of above dependencies. The user is no more required to install these dependencies manually. 

(3) As there is something corrupted in your OS, please write OS image to your microSD card again to have a clean OS. Run the ad2 installation script on the new OS.
